version: '3.3'

services:
    db:
      image: postgres
      restart: always
      environment:
        - POSTGRES_PASSWORD=PASWORD
        - POSTGRES_USER=USERNAME
        - POSTGRES_DB=DATABASE
      ports:
        - 5432:5432
      volumes:
        - ./db-data:/var/lib/postgresql/data
      networks:
        - postgres-network
    metabase:
      volumes:
        - ./metabase-data:/metabase-data
      environment:
        - MB_DB_FILE=/metabase-data/metabase.db
        - MB_DB_TYPE=postgres
        - MB_DB_DBNAME=DATABASE
        - MB_DB_PORT=5432
        - MB_DB_USER=USERNAME
        - MB_DB_PASS=PASWORD
        - MB_DB_HOST=db
      ports:
        - 3000:3000
      image: metabase/metabase
      restart: always
      depends_on: 
        - db
      networks:
        - postgres-network
networks:
  postgres-network:
    driver: bridge

volumes:
  db-data:
  metabase-data: